myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('',views.index,name='index')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from joblib import load
from django.conf import settings
import os
import pickle
import pandas as pd

model_path = os.path.join(settings.BASE_DIR, 'saveModel', 'rf_model.pkl')

# Create your views here.
def index(request):

    context ={'result':None}

    if request.method=='POST':

        with open(model_path,'rb') as file:
            ml_model = pickle.load(file) 

        weight=request.POST.get('weight')
        length=request.POST.get('length')
        circumference=request.POST.get('circumference')

        input_data = pd.DataFrame({
            'Weight': [weight],
            'Length': [length],
            'Circumference': [circumference]
        })

        mango_result = ml_model.predict(input_data)

        if mango_result == 0:
            y_preds = 'Grade A'
        elif mango_result == 1:
            y_preds = 'Grade B'
        else:
            y_preds ='Grade C'
        
        context['result'] = y_preds

    return render(request,'myapp/index.html',context=context)

myapp/templates/myapp/index.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Index Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-1 mt-4">
            <form method="POST" action="{% url "myapp:index" %}">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="weight" class="form-label">Weight (g)</label>
                  <input type="number" class="form-control" id="weight" min="0" step="0.1" name="weight" required>
                </div>
                
                <div class="mb-3">
                    <label for="length" class="form-label">Length (cm)</label>
                    <input type="number" class="form-control" id="length" min="0" step="0.1" name="length" required>
                </div>

                <div class="mb-3">
                    <label for="circumference" class="form-label">Circumference (cm)</label>
                    <input type="number" class="form-control" id="circumference" min="0" step="0.1" name="circumference" required>
                </div>

                <button type="Submit" class="btn btn-primary w-100" >Submit</button>
              </form>
        </div>
    </div>
</div>

{% if result %}
<p>Harumanis Mango: {{result}}</p>
{% else %}
No input yet
{% endif %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>